### ISSUE TITLE
unsup is a class in 03

### ISSUE THREAD

**Issue by thomasjpfan** [amueller/ml-workshop-4-of-4#1]
A bit strange how the unlabeled data is considered a label for the notebook.

```
reviews_train = load_files("data/aclImdb/train/", categories=['neg', 'pos'])
```

**Comment by amueller** [comment]
categories allows you to drop it? really? maybe I should have read the docs at some point. lol. actually I kind of remember that, but both here *and in the book* i'm telling people to remove the folder.
Please PR? and raise an issue on the book and/or report on the O'Reilly tracker?
